#define sRecon 0
#define sAcolyte 1
#define sMimic 2
#define sLeech 3
#define sACV 4
#define sMCV 5
#define sRammingFrigate 6
#define sMultiBeamFrigate 7
#define sHiveFrigate 8
#define sSwarmer 9
#define sDreadnought 10
#define sDreadnoughtCannon 11
#define sCarrier 12
#define sCarrierSupport 13
#define sWorker 14
#define sRepairDroid 15
#define sProcessor 16
#define sSentinel 17
#define sMothership 18
#define sMothershipSpecial 19
#define sMothershipEngineering 20
#define sMothershipArmour 21
#define sMothershipMicro 22
#define sMothershipWeapons 23
#define sMothershipDockingBay 24
#define sDestroyer 25
#define sMothershipSupport 26
#define sMothershipCommand 27
#define sMothershipEnginesLower 28
#define sMothershipEnginesUpper 29
#define sMothershipLowerSpine 30
#define sMothershipBigGun 31
#define sMothershipOreCanArmour 32
#define bRecon 33
#define bAcolyte 34
#define bInterceptor 35
#define bCloakedFighter 36
#define bAttackBomber 37
#define bACV 38
#define bMultiGunCorvette 39
#define bHeavyCorvette 40
#define bMultiBeamFrigate 41
#define bHiveFrigate 42
#define bSwarmer 43
#define bIonArrayFrigate 44
#define bDFGFrigate 45
#define bHeavyCruiser 46
#define bCarrier 47
#define bRammingFrigate 48
#define bWorker 49
#define bRepairDroid 50
#define bProcessor 51
#define bSentinel 52
#define bMothership 53
#define bMothershipDockingBay 54
#define bMothershipEnginesLower 55
#define bSectMoship 56
#define bMothershipSupport 57
#define bCruiseMissile 58
#define bMissileCorvette 59
#define kAdvanceSupportFrigate 60
#define kAttackBomber 61
#define kCarrier 62
#define kCloakGenerator 63
#define kGravWellGenerator 64
#define kHeavyCorvette 65
#define kHeavyCruiser 66
#define kHeavyDefender 67
#define kHeavyInterceptor 68
#define kIonCannonFrigate 69
#define kMultiGunCorvette 70
#define kProximitySensor 71
#define kSalCapCorvette 72
#define kStandardDestroyer 73
#define tAdvanceSupportFrigate 74
#define tAttackBomber 75
#define tCarrier 76
#define tCloakGenerator 77
#define tDFGFrigate 78
#define tGravWellGenerator 79
#define tHeavyCruiser 80
#define tHeavyDefender 81
#define tHeavyInterceptor 82
#define tIonCannonFrigate 83
#define tMinelayerCorvette 84
#define tMissileDestroyer 85
#define tMultiGunCorvette 86
#define tProximitySensor 87
#define tResourceCollector 88
#define tSalCapCorvette 89
#define tStandardDestroyer 90
#define tStandardFrigate 91
#define p1Outpost 92
#define p1Fighter 93
#define p1IonArrayFrigate 94
#define p1MissileCorvette 95
#define p1Mothership 96
#define p1StandardCorvette 97
#define trFloatingCity 98
#define trCargoBarge 99
#define trMiningBase 100
#define trResearchStation 101
#define trJunkYardDawg 102
#define trJunkYardHQ 103
#define trGhostship 104
#define trJunk_LGun 105
#define trJunk_SGun 106
#define trResearchStationBridge 107
#define trResearchStationTower 108
#define dRKO 109
#define dBigGun 110
#define dBigGunUnit 111
#define dSlipgateSmall 112
#define dSlipgateMedium 113
#define dSlipgateLarge 114
#define dCrate 115
#define dJunk1PartA 116
#define dJunk1Shell 117
#define dJunk1Strut 118
#define dJunk2Shipwreck 119
#define dJunk3Boiler 120
#define dJunk3BoilerCasing 121
#define dMessagePod 122
#define dBuoy 123
#define dFirstPlanet 124
#define dDeadPlanet 125
#define dCrystal0 126
#define dCrystal1 127
#define dBeastDockingBay 128
#define dNISBuoy 129
#define dBeastMothership 130
#define dNomadMoon 131
#define dNomadFieldEmitter 132
#define dAcolyte 133
#define dPrisonShip 134
#define dPrisonShipInfected 135
#define dSlipgateNode 136
#define dKushanCarrier 137
#define dIonArrayFrigate 138
#define dIonCannonFrigate 139
#define dEcclesiam 140
#define dEcclesiamInfected 141
#define nisLightSource1 142
#define nisLightSource2 143
#define nisLensflareSource1 144

#define STD_FIRST_SHIP sRecon
#define STD_LAST_SHIP bMissileCorvette

#define TOTAL_NUM_SHIPS 145

#define TOTAL_STD_SHIPS (STD_LAST_SHIP - STD_FIRST_SHIP + 1)